name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      
      - name: Run tests
        run: npm run test -- --run
      
      - name: Build extension
        run: npm run build:prod
      
      - name: Get version
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Building version $VERSION"
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.VERSION }}
          name: Release v${{ steps.version.outputs.VERSION }}
          draft: false
          prerelease: false
          files: |
            chrome-extension.zip
            build/RELEASE-NOTES-v*.md
          body: |
            ## Chrome Home Extension v${{ steps.version.outputs.VERSION }}
            
            ### Installation
            1. Download `chrome-extension.zip`
            2. Extract the archive
            3. Open Chrome and go to `chrome://extensions/`
            4. Enable Developer Mode
            5. Click "Load unpacked" and select the extracted folder
            
            ### What's New
            See the [Changelog](CHANGELOG.md) for details.
      
      - name: Upload to Chrome Web Store
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Ready for manual upload to Chrome Web Store"
          echo "Download the release artifact and upload at:"
          echo "https://chrome.google.com/webstore/devconsole"